CREATE TABLE MANUFACTURERS (
    MANUFACTURER_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    CODE CHAR(3) UNIQUE NOT NULL,
    NAME VARCHAR(32) NOT NULL,
    CITY VARCHAR(32) NOT NULL,
    STATE CHAR(2),
    COUNTRY CHAR(2) NOT NULL,
    WEBSITE VARCHAR(256)
);

CREATE TABLE MODELS (
    SKU VARCHAR(32) PRIMARY KEY,
    MANUFACTURER_ID BIGINT NOT NULL,
    FAMILY VARCHAR(32) NOT NULL,
    MODEL VARCHAR(32),
    CATEGORY VARCHAR(32) NOT NULL,
    CALIBER VARCHAR(16) NOT NULL,
    CAPACITY INT,
    BARREL_LENGTH INT NOT NULL,
    EXTERNAL_SAFETY BOOLEAN NOT NULL,
    OPTICS_READY BOOLEAN NOT NULL,
    SIGHTS VARCHAR(32),
    COLOR VARCHAR(32)
);

ALTER TABLE MODELS ADD FOREIGN KEY (MANUFACTURER_ID) REFERENCES MANUFACTURERS(MANUFACTURER_ID);